<?php

namespace EntityBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL($id)
    {
        $dqlresult = $this->getEntityManager()
            ->createQuery("SELECT a
                               FROM 
                                    EntityBundle:Answer a
                               WHERE
                                    a.user = '$id'
                                  
                              ");
        return $dqlresult->getResult();
    }
}
