<?php

namespace EntityBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByScore()
    {
        $query=$this->getEntityManager()
            ->createQuery("
            select sum(score) from EntityBundle:Answer res
            group by idUser");
        return $query->getResult();
    }
}
