<?php

namespace EntityBundle\Repository;

/**
 * EvaluationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationsRepository extends \Doctrine\ORM\EntityRepository
{
}
