<?php

namespace EntityBundle\Repository;

/**
 * lignePanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignePanierRepository extends \Doctrine\ORM\EntityRepository
{
}
