<?php

namespace EntityBundle\Repository;

/**
 * MetapostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetapostRepository extends \Doctrine\ORM\EntityRepository
{
}
