<?php

namespace EntityBundle\Repository;

/**
 * ValidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidateRepository extends \Doctrine\ORM\EntityRepository
{
}
